name: iOS-IPA-Build

on:
  workflow_dispatch:            # manual trigger only

jobs:
  build-ios:
    runs-on: macos-latest       # macOS 14, Xcode 15, Swift 5.9

    steps:
      # 1 – Checkout repo
      - uses: actions/checkout@v3

      # 2 – Install Flutter (stable)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      # 3 – Clean & fetch pub packages
      - name: Flutter clean / pub get
        run: |
          flutter clean
          flutter pub get
        working-directory: mobileapp

      # 4 – Reset Pods, ensure platform iOS 13
      - name: Prepare iOS folder
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          [ -f Podfile ] || pod init
          if grep -q '^platform :ios' Podfile; then
            sed -i '' "s/^platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            sed -i '' "1s/^/platform :ios, '13.0'\n/" Podfile
          fi
        working-directory: mobileapp

      # 5 – Add static-frameworks + modular headers + Swift 5.9
      - name: Patch Podfile
        run: |
          cd mobileapp/ios

          # ----- make sure we have use_frameworks! :static & use_modular_headers! -----
          if ! grep -q 'use_frameworks! :linkage => :static' Podfile; then
            printf "\nuse_frameworks! :linkage => :static\n" >> Podfile
          fi

          if ! grep -q 'use_modular_headers!' Podfile; then
            printf "use_modular_headers!\n" >> Podfile
          fi

          # ----- wipe any old post_install and add a fresh one -----
          sed -i '' '/post_install do/,/^end$/d' Podfile
          cat >> Podfile <<'RUBY'
post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      c.build_settings['SWIFT_VERSION']              = '5.9'
    end
  end
end
RUBY

      # 6 – Install pods
      - run: pod install --repo-update
        working-directory: mobileapp/ios

      # 7 – Build unsigned release
      - run: flutter build ios --release --no-codesign
        working-directory: mobileapp

      # 8 – Package Runner.app → IPA
      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
        working-directory: mobileapp

      # 9 – Upload IPA to a GitHub Release
      - name: Upload IPA
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobileapp/build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          tag: ios-build-${{ github.run_number }}
          overwrite: true
          body: |
            🎉 Unsigned iOS IPA for run #${{ github.run_number }}
