name: iOS-ipa-build

on:
  workflow_dispatch:            # run manually from the Actions tab

jobs:
  build-ios:
    name: "🎉  iOS Build"
    runs-on: macos-latest       # Xcode 15, Swift 5.9, CocoaPods pre-installed

    steps:
      # 1  Check out code
      - uses: actions/checkout@v3

      # 2  Install Flutter (stable)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      # 3  Clean + resolve pub packages
      - name: Flutter clean / pub get
        run: |
          flutter clean
          flutter pub get
        working-directory: mobileapp

      # 4  Reset Pods and be sure the Podfile targets iOS 13
      - name: Prepare iOS folder
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          [ -f Podfile ] || pod init
          # Ensure: platform :ios, '13.0'
          if grep -q "^platform :ios" Podfile; then
            sed -i '' "s/^platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            sed -i '' '1s/^/platform :ios, '\''13.0'\''\n/' Podfile
          fi
        working-directory: mobileapp

      # 5  Add a fresh post_install block that forces Swift 5.9
      - name: Patch Podfile for Swift 5.9
        run: |
          cd mobileapp/ios
          # Remove any previous post_install
          sed -i '' '/post_install do/,/^end$/d' Podfile
          # Append a new one line-by-line (avoids YAML heredoc issues)
          {
            printf "\npost_install do |installer|\n"
            printf "  installer.pods_project.targets.each do |target|\n"
            printf "    target.build_configurations.each do |config|\n"
            printf "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'\n"
            printf "      config.build_settings['SWIFT_VERSION']              = '5.9'\n"
            printf "    end\n"
            printf "  end\n"
            printf "end\n"
          } >> Podfile
          echo "=== Podfile now ==="
          cat Podfile

      # 6  Install pods
      - run: pod install --repo-update
        working-directory: mobileapp/ios

      # 7  Build unsigned release
      - run: flutter build ios --release --no-codesign
        working-directory: mobileapp

      # 8  Package Runner.app → IPA
      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
        working-directory: mobileapp

      # 9  Upload IPA to a release tagged for this run
      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobileapp/build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          tag: ios-build-${{ github.run_number }}
          overwrite: true
          body: |
            🎉 Unsigned iOS IPA for run #${{ github.run_number }}
